/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dcic_Rd600 */

#ifndef _Included_dcic_Rd600
#define _Included_dcic_Rd600
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dcic_Rd600
 * Method:    IC_InitComm
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1InitComm
  (JNIEnv *, jobject, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ExitComm
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ExitComm
  (JNIEnv *, jobject, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Status
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Status
  (JNIEnv *, jobject, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_InitType
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1InitType
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Down
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Down
  (JNIEnv *, jobject, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_InitCommAdvanced
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1InitCommAdvanced
  (JNIEnv *, jobject, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Reset
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Reset
  (JNIEnv *, jobject, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_DevBeep
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1DevBeep
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ReadVer
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ReadVer
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ReadDevice
 * Signature: (ISS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ReadDevice
  (JNIEnv *, jobject, jint, jshort, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_WriteDevice
 * Signature: (ISS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1WriteDevice
  (JNIEnv *, jobject, jint, jshort, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ReadDevice_Hex
 * Signature: (ISS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ReadDevice_1Hex
  (JNIEnv *, jobject, jint, jshort, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_WriteDevice_Hex
 * Signature: (ISS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1WriteDevice_1Hex
  (JNIEnv *, jobject, jint, jshort, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Encrypt
 * Signature: ([C[CS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Encrypt
  (JNIEnv *, jobject, jcharArray, jcharArray, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Decrypt
 * Signature: ([C[CS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Decrypt
  (JNIEnv *, jobject, jcharArray, jcharArray, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Encrypt_Hex
 * Signature: ([C[CS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Encrypt_1Hex
  (JNIEnv *, jobject, jcharArray, jcharArray, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Decrypt_Hex
 * Signature: ([C[CS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Decrypt_1Hex
  (JNIEnv *, jobject, jcharArray, jcharArray, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_InitComm_Baud
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1InitComm_1Baud
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_SetCommTimeout
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1SetCommTimeout
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CpuReset
 * Signature: (I[C[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CpuReset
  (JNIEnv *, jobject, jint, jcharArray, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CpuApdu
 * Signature: (IC[C[C[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CpuApdu
  (JNIEnv *, jobject, jint, jchar, jcharArray, jcharArray, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CpuApduSource
 * Signature: (IC[C[C[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CpuApduSource
  (JNIEnv *, jobject, jint, jchar, jcharArray, jcharArray, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CpuReset_Hex
 * Signature: (I[C[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CpuReset_1Hex
  (JNIEnv *, jobject, jint, jcharArray, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CpuApdu_Hex
 * Signature: (IC[C[C[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CpuApdu_1Hex
  (JNIEnv *, jobject, jint, jchar, jcharArray, jcharArray, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CpuApduSource_Hex
 * Signature: (IC[C[C[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CpuApduSource_1Hex
  (JNIEnv *, jobject, jint, jchar, jcharArray, jcharArray, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CpuGetProtocol
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CpuGetProtocol
  (JNIEnv *, jobject, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CpuApduRespon
 * Signature: (IC[C[C[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CpuApduRespon
  (JNIEnv *, jobject, jint, jchar, jcharArray, jcharArray, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CpuSetProtocol
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CpuSetProtocol
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     dcic_Rd600
 * Method:    ReadCount_SLE4442
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_ReadCount_1SLE4442
  (JNIEnv *, jobject, jint);

/*
 * Class:     dcic_Rd600
 * Method:    CheckPass_4442hex
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_CheckPass_14442hex
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    ChangePass_4442hex
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_ChangePass_14442hex
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    CheckPass_SLE4442
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_CheckPass_1SLE4442
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    ChangePass_SLE4442
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_ChangePass_1SLE4442
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    ReadPass_SLE4442
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_ReadPass_1SLE4442
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    ReadPass_4442hex
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_ReadPass_14442hex
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    ReadWithProtection_SLE4442
 * Signature: (ISS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_ReadWithProtection_1SLE4442
  (JNIEnv *, jobject, jint, jshort, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    WriteWithProtection_SLE4442
 * Signature: (ISS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_WriteWithProtection_1SLE4442
  (JNIEnv *, jobject, jint, jshort, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    ReadCount_SLE4428
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_ReadCount_1SLE4428
  (JNIEnv *, jobject, jint);

/*
 * Class:     dcic_Rd600
 * Method:    CheckPass_4428hex
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_CheckPass_14428hex
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    ChangePass_4428hex
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_ChangePass_14428hex
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    CheckPass_SLE4428
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_CheckPass_1SLE4428
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    ChangePass_SLE4428
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_ChangePass_1SLE4428
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    ReadWithProtection_SLE4428
 * Signature: (ISS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_ReadWithProtection_1SLE4428
  (JNIEnv *, jobject, jint, jshort, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    WriteWithProtection_SLE4428
 * Signature: (ISS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_WriteWithProtection_1SLE4428
  (JNIEnv *, jobject, jint, jshort, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Read_Hex
 * Signature: (III[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Read_1Hex
  (JNIEnv *, jobject, jint, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Read
 * Signature: (III[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Read
  (JNIEnv *, jobject, jint, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Write_Hex
 * Signature: (III[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Write_1Hex
  (JNIEnv *, jobject, jint, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Write
 * Signature: (III[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Write
  (JNIEnv *, jobject, jint, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Erase
 * Signature: (ISS)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Erase
  (JNIEnv *, jobject, jint, jshort, jshort);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Erase_102
 * Signature: (ISS)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Erase_1102
  (JNIEnv *, jobject, jint, jshort, jshort);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Fuse_102
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Fuse_1102
  (JNIEnv *, jobject, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ReadCount_102
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ReadCount_1102
  (JNIEnv *, jobject, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CheckPass_102
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CheckPass_1102
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ChangePass_102
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ChangePass_1102
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CheckAZPass_102
 * Signature: (IS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CheckAZPass_1102
  (JNIEnv *, jobject, jint, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ChangeAZPass_102
 * Signature: (IS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ChangeAZPass_1102
  (JNIEnv *, jobject, jint, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CheckPass_102hex
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CheckPass_1102hex
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ChangePass_102hex
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ChangePass_1102hex
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CheckAZPass_102hex
 * Signature: (IS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CheckAZPass_1102hex
  (JNIEnv *, jobject, jint, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ChangeAZPass_102hex
 * Signature: (IS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ChangeAZPass_1102hex
  (JNIEnv *, jobject, jint, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Write24_Hex
 * Signature: (III[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Write24_1Hex
  (JNIEnv *, jobject, jint, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Write24
 * Signature: (III[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Write24
  (JNIEnv *, jobject, jint, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Write64_Hex
 * Signature: (III[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Write64_1Hex
  (JNIEnv *, jobject, jint, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Write64
 * Signature: (III[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Write64
  (JNIEnv *, jobject, jint, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_DirectRead
 * Signature: (ISSS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1DirectRead
  (JNIEnv *, jobject, jint, jshort, jshort, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_DirectWrite
 * Signature: (ISSS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1DirectWrite
  (JNIEnv *, jobject, jint, jshort, jshort, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_DirectRead_Hex
 * Signature: (ISSS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1DirectRead_1Hex
  (JNIEnv *, jobject, jint, jshort, jshort, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_DirectWrite_Hex
 * Signature: (ISSS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1DirectWrite_1Hex
  (JNIEnv *, jobject, jint, jshort, jshort, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Read_1101
 * Signature: (ISSS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Read_11101
  (JNIEnv *, jobject, jint, jshort, jshort, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Write_1101
 * Signature: (ISSS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Write_11101
  (JNIEnv *, jobject, jint, jshort, jshort, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Read_1101hex
 * Signature: (ISSS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Read_11101hex
  (JNIEnv *, jobject, jint, jshort, jshort, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Write_1101hex
 * Signature: (ISSS[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Write_11101hex
  (JNIEnv *, jobject, jint, jshort, jshort, jshort, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Fuse_4404
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Fuse_14404
  (JNIEnv *, jobject, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ReadCount_4404
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ReadCount_14404
  (JNIEnv *, jobject, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CheckPass_4404
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CheckPass_14404
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ChangePass_4404
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ChangePass_14404
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CheckAZPass_4404
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CheckAZPass_14404
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ChangeAZPass_4404
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ChangeAZPass_14404
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CheckPass_4404hex
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CheckPass_14404hex
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ChangePass_4404hex
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ChangePass_14404hex
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CheckAZPass_4404hex
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CheckAZPass_14404hex
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ChangeAZPass_4404hex
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ChangeAZPass_14404hex
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_RValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1RValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_DEValue
 * Signature: (IS)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1DEValue
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Fuse_4406
 * Signature: (IS)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Fuse_14406
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ReadCount_4406
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ReadCount_14406
  (JNIEnv *, jobject, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CheckPass_4406
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CheckPass_14406
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Erase_4406
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Erase_14406
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CheckPass_4406hex
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CheckPass_14406hex
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CheckPass_4406userhex
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CheckPass_14406userhex
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CheckPass_4406user
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CheckPass_14406user
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Fuse_1604
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Fuse_11604
  (JNIEnv *, jobject, jint);

/*
 * Class:     dcic_Rd600
 * Method:    ReadCount_1604
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_ReadCount_11604
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dcic_Rd600
 * Method:    CheckPass_1604hex
 * Signature: (II[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_CheckPass_11604hex
  (JNIEnv *, jobject, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    ChangePass_1604hex
 * Signature: (II[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_ChangePass_11604hex
  (JNIEnv *, jobject, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    CheckPass_1604
 * Signature: (II[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_CheckPass_11604
  (JNIEnv *, jobject, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    ChangePass_1604
 * Signature: (II[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_ChangePass_11604
  (JNIEnv *, jobject, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_Fuse_1604B
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1Fuse_11604B
  (JNIEnv *, jobject, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ReadCount_1604B
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ReadCount_11604B
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CheckPass_1604Bhex
 * Signature: (II[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CheckPass_11604Bhex
  (JNIEnv *, jobject, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ChangePass_1604Bhex
 * Signature: (II[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ChangePass_11604Bhex
  (JNIEnv *, jobject, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CheckPass_1604B
 * Signature: (II[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CheckPass_11604B
  (JNIEnv *, jobject, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ChangePass_1604B
 * Signature: (II[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ChangePass_11604B
  (JNIEnv *, jobject, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CheckRPassword_Hex
 * Signature: (II[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CheckRPassword_1Hex
  (JNIEnv *, jobject, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CheckWPassword_Hex
 * Signature: (II[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CheckWPassword_1Hex
  (JNIEnv *, jobject, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CheckRPassword
 * Signature: (II[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CheckRPassword
  (JNIEnv *, jobject, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_CheckWPassword
 * Signature: (II[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1CheckWPassword
  (JNIEnv *, jobject, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ChangeRPassword_Hex
 * Signature: (II[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ChangeRPassword_1Hex
  (JNIEnv *, jobject, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ChangeWPassword_Hex
 * Signature: (II[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ChangeWPassword_1Hex
  (JNIEnv *, jobject, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ChangeRPassword
 * Signature: (II[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ChangeRPassword
  (JNIEnv *, jobject, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ChangeWPassword
 * Signature: (II[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ChangeWPassword
  (JNIEnv *, jobject, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_WriteFuse
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1WriteFuse
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ReadFuse
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ReadFuse
  (JNIEnv *, jobject, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_WriteUserZone
 * Signature: (III[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1WriteUserZone
  (JNIEnv *, jobject, jint, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_WriteConfigZone
 * Signature: (III[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1WriteConfigZone
  (JNIEnv *, jobject, jint, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_WriteUserZone_Hex
 * Signature: (III[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1WriteUserZone_1Hex
  (JNIEnv *, jobject, jint, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_WriteConfigZone_Hex
 * Signature: (III[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1WriteConfigZone_1Hex
  (JNIEnv *, jobject, jint, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ReadUserZone
 * Signature: (III[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ReadUserZone
  (JNIEnv *, jobject, jint, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ReadConfigZone
 * Signature: (III[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ReadConfigZone
  (JNIEnv *, jobject, jint, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ReadUserZone_Hex
 * Signature: (III[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ReadUserZone_1Hex
  (JNIEnv *, jobject, jint, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ReadConfigZone_Hex
 * Signature: (III[C)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ReadConfigZone_1Hex
  (JNIEnv *, jobject, jint, jint, jint, jcharArray);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ReadWPasswordCount
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ReadWPasswordCount
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_ReadRPasswordCount
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1ReadRPasswordCount
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dcic_Rd600
 * Method:    IC_SetUserZone
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_IC_1SetUserZone
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dcic_Rd600
 * Method:    hex2asc
 * Signature: ([C[CS)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_hex2asc
  (JNIEnv *, jobject, jcharArray, jcharArray, jshort);

/*
 * Class:     dcic_Rd600
 * Method:    asc2hex
 * Signature: ([C[CS)I
 */
JNIEXPORT jint JNICALL Java_dcic_Rd600_asc2hex
  (JNIEnv *, jobject, jcharArray, jcharArray, jshort);

#ifdef __cplusplus
}
#endif
#endif
